'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'SLY_Assistant.user.js'), 'utf8');
function extract(name) {
  const start = source.indexOf(`function ${name}(`); assert.notEqual(start, -1, name);
  const body = source.indexOf('{', source.indexOf(')', start)); let depth=0,q='',esc=false;
  for(let i=body;i<source.length;i++){const c=source[i];if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q='';continue;}if('"\'`'.includes(c)){q=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return source.slice(start,i+1);} throw Error(name);
}
function api(){const c=vm.createContext({Map,Object,Array,JSON,String,Number,Math,BigInt,getSlyaInfluxInstanceTag:()=> 'MUD',getUpgradeAutomationInfluxFactionTag:()=> 'MUD',influxEscape:String,optimizationInfluxString:v=>JSON.stringify(String(v??''))});vm.runInContext(`${extract('getSlyaCostEventTimestamp')}\n${extract('buildSlyaFuelCostSourceEvent')}\n${extract('getSlyaTransactionFeeSourceEvents')}\n${extract('buildSlyaCostSourceEventLine')}\n${extract('normalizeSlyaCostSourceOutbox')}\n${extract('snapshotSlyaCostSourceOutbox')}\n${extract('acknowledgeSlyaCostSourceEventSnapshot')}\n${extract('composeSlyaScheduledInfluxBody')}\nthis.api={buildSlyaFuelCostSourceEvent,getSlyaTransactionFeeSourceEvents,buildSlyaCostSourceEventLine,normalizeSlyaCostSourceOutbox,snapshotSlyaCostSourceOutbox,acknowledgeSlyaCostSourceEventSnapshot,composeSlyaScheduledInfluxBody};`,c);return c.api;}
const tx=(sig,fee=5000,time=1785830000)=>({slyaTxHash:sig,slyaTxFeeLamports:fee,blockTime:time});
const fuelInput={cycleId:'cycle',movementEventId:'cycle:0',movementIndex:0,burnedFuel:12.5,txResult:tx('move'),fleetAccount:'fleet',fleetLabel:'Fleet',assignment:'Transport'};
test('confirmed Fuel and SOL reach scheduled body and distinct equal-time events remain distinct',()=>{const a=api();const fuel=a.buildSlyaFuelCostSourceEvent(fuelInput);const sol=a.getSlyaTransactionFeeSourceEvents(tx('real'))[0];const out=a.normalizeSlyaCostSourceOutbox({[fuel.eventIdentity]:a.buildSlyaCostSourceEventLine(fuel),[sol.eventIdentity]:a.buildSlyaCostSourceEventLine(sol)});const snap=a.snapshotSlyaCostSourceOutbox(out);const body=a.composeSlyaScheduledInfluxBody('compat x=1i',snap);assert.match(body,/cargo_cost_source_event_v1.*fuel:cycle:0/);assert.match(body,/cargo_cost_source_event_v1.*sol_fee:real/);assert.match(body,/compat x=1i/);assert.equal(snap.length,2);});
test('ack removes exactly snapshot; post-snapshot event remains',()=>{const a=api();const out=a.normalizeSlyaCostSourceOutbox({a:'cargo_cost_source_event_v1,a',b:'cargo_cost_source_event_v1,b'});const snap=a.snapshotSlyaCostSourceOutbox(out);out.set('c','cargo_cost_source_event_v1,c');a.acknowledgeSlyaCostSourceEventSnapshot(out,snap);assert.deepEqual([...out.entries()],[['c','cargo_cost_source_event_v1,c']]);});
test('failure retention, restart reload, and replay dedupe are durable map semantics',()=>{const a=api();let out=a.normalizeSlyaCostSourceOutbox({a:'cargo_cost_source_event_v1,a'});const snap=a.snapshotSlyaCostSourceOutbox(out);assert.equal(out.size,1);out=a.normalizeSlyaCostSourceOutbox(Object.fromEntries(out));out.set('a','cargo_cost_source_event_v1,a');assert.equal(out.size,1);assert.equal(snap.length,1);});
test('production path persists outbox and only schedules it into established optimization bucket writes',()=>{assert.match(source,/SLYA_COST_SOURCE_OUTBOX_KEY/);assert.match(source,/GM\.setValue\(SLYA_COST_SOURCE_OUTBOX_KEY/);assert.match(source,/bucketOverride === UPGRADE_AUTOMATION_INFLUX_BUCKET/);assert.match(source,/acknowledgeSlyaCostSourceEventSnapshot/);assert.doesNotMatch(source,/fetch\([^\n]*cargo_cost_source_event_v1|setInterval\([^\n]*cargo_cost_source_event_v1/);});
test('both userscript copies remain synchronized for outbox implementation',()=>{const electron=fs.readFileSync(path.join(__dirname,'..','electron-app/app/SLY_Assistant.user.js'),'utf8');for(const name of ['normalizeSlyaCostSourceOutbox','snapshotSlyaCostSourceOutbox','acknowledgeSlyaCostSourceEventSnapshot','composeSlyaScheduledInfluxBody'])assert.ok(electron.includes(`function ${name}(`));});
