'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'SLY_Assistant.user.js'), 'utf8');
function extract(name) {
  const start = source.indexOf(`function ${name}(`); assert.notEqual(start, -1, name);
  const body = source.indexOf('{', source.indexOf(')', start)); let depth=0,q='',esc=false;
  for(let i=body;i<source.length;i++){const c=source[i];if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q='';continue;}if('"\'`'.includes(c)){q=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return source.slice(start,i+1);} throw Error(name);
}
function api(){const c=vm.createContext({Map,Object,Array,JSON,String,Number,Math,BigInt,URL,Date,globalSettings:{influxURL:'https://example.invalid/api/v2/write?bucket=slya&precision=ms'},getSlyaInfluxInstanceTag:()=> 'MUD',getUpgradeAutomationInfluxFactionTag:()=> 'MUD',influxEscape:String,optimizationInfluxString:v=>JSON.stringify(String(v??''))});vm.runInContext(`const SLYA_COST_SOURCE_RETRY_BASE_MS=30000; const SLYA_COST_SOURCE_RETRY_MAX_MS=900000;\n${extract('getSlyaInfluxPrecision')}\n${extract('formatSlyaInfluxTimestamp')}\n${extract('normalizeSlyaCostSourceEventLineTimestamp')}\n${extract('getSlyaCostSourceScope')}\n${extract('getSlyaCostEventTimestamp')}\n${extract('buildSlyaFuelCostSourceEvent')}\n${extract('getSlyaTransactionFeeSourceEvents')}\n${extract('buildSlyaCostSourceEventLine')}\n${extract('normalizeSlyaCostSourceOutbox')}\n${extract('snapshotSlyaCostSourceOutbox')}\n${extract('parseSlyaCostSourceRetryAfterMs')}\n${extract('deferSlyaCostSourceEventSnapshot')}\n${extract('acknowledgeSlyaCostSourceEventSnapshot')}\n${extract('composeSlyaScheduledInfluxBody')}\n${extract('getSlyaCostSourceOldestPendingAgeSeconds')}\n${extract('sanitizeSlyaCostSourceInfluxError')}\nthis.api={formatSlyaInfluxTimestamp,normalizeSlyaCostSourceEventLineTimestamp,buildSlyaFuelCostSourceEvent,getSlyaTransactionFeeSourceEvents,buildSlyaCostSourceEventLine,normalizeSlyaCostSourceOutbox,snapshotSlyaCostSourceOutbox,parseSlyaCostSourceRetryAfterMs,deferSlyaCostSourceEventSnapshot,acknowledgeSlyaCostSourceEventSnapshot,composeSlyaScheduledInfluxBody,getSlyaCostSourceOldestPendingAgeSeconds,sanitizeSlyaCostSourceInfluxError};`,c);return c.api;}
const tx=(sig,fee=5000,time=1785830000)=>({slyaTxHash:sig,slyaTxFeeLamports:fee,blockTime:time,slyaFleetAccount:'fleet',slyaFleetLabel:'Fleet',slyaAssignment:'Transport'});
const fuelInput={cycleId:'cycle',movementEventId:'cycle:0',movementIndex:0,burnedFuel:12.5,txResult:tx('move'),fleetAccount:'fleet',fleetLabel:'Fleet',assignment:'Transport'};
test('confirmed Fuel and SOL reach normal body and distinct equal-time events remain distinct',()=>{const a=api();const fuel=a.buildSlyaFuelCostSourceEvent(fuelInput);const sol=a.getSlyaTransactionFeeSourceEvents(tx('real'))[0];const out=a.normalizeSlyaCostSourceOutbox({[fuel.eventIdentity]:a.buildSlyaCostSourceEventLine(fuel),[sol.eventIdentity]:a.buildSlyaCostSourceEventLine(sol)});const snap=a.snapshotSlyaCostSourceOutbox(out);const body=a.composeSlyaScheduledInfluxBody('compat x=1i',snap);assert.match(body,/cargo_cost_source_event_v1.*fuel:cycle:0/);assert.match(body,/cargo_cost_source_event_v1.*sol_fee:real/);assert.match(body,/compat x=1i/);assert.match(body,/ 1785830000000(?:\n|$)/);assert.equal(snap.length,2);});
test('legacy outbox strings migrate to durable records with queued time',()=>{const a=api();const legacy='cargo_cost_source_event_v1,eventType=sol_fee,eventIdentity=sol_fee:sig,schemaVersion=1 txFeeLamports=5000i,transactionSignature="sig" 1785830000000000000';const migrated=a.normalizeSlyaCostSourceOutbox({['sol_fee:sig']:legacy}).get('sol_fee:sig');assert.equal(migrated.line,'cargo_cost_source_event_v1,eventType=sol_fee,eventIdentity=sol_fee:sig,schemaVersion=1 txFeeLamports=5000i,transactionSignature="sig" 1785830000000');assert.ok(Number.isSafeInteger(migrated.queuedAtMs));});
test('ack removes exactly accepted snapshot; post-snapshot event remains',()=>{const a=api();const out=a.normalizeSlyaCostSourceOutbox({a:'cargo_cost_source_event_v1,a',b:'cargo_cost_source_event_v1,b'});const snap=a.snapshotSlyaCostSourceOutbox(out);out.set('c',{line:'cargo_cost_source_event_v1,c',queuedAtMs:3});a.acknowledgeSlyaCostSourceEventSnapshot(out,snap);assert.deepEqual([...out.entries()],[['c',{line:'cargo_cost_source_event_v1,c',queuedAtMs:3}]]);});
test('failure retention, restart reload, deterministic dedupe, and pending age are durable',()=>{const a=api();let out=a.normalizeSlyaCostSourceOutbox({a:{line:'cargo_cost_source_event_v1,a',queuedAtMs:1000}});const snap=a.snapshotSlyaCostSourceOutbox(out);assert.equal(out.size,1);out=a.normalizeSlyaCostSourceOutbox(Object.fromEntries(out));if(!out.has('a')) out.set('a',{line:'cargo_cost_source_event_v1,a',queuedAtMs:2000});assert.equal(out.size,1);assert.equal(out.get('a').queuedAtMs,1000);assert.equal(a.getSlyaCostSourceOldestPendingAgeSeconds(out,6000),5);assert.equal(snap.length,1);});
test('Influx rejection diagnostic retains parser reason but redacts payload and identifiers',()=>{const a=api();const secret='5KGXNWa5URbQJKiUuRH4D4nQ581QKfzvUkgpfA98hm3WSs9yi3zJqJtb4bHm4GxfQysBpKzPqh186VXDA1u2j8Zn';const raw=JSON.stringify({code:'invalid',message:`unable to parse 'cargo_cost_source_event_v1,eventIdentity=sol_fee:${secret} txFeeLamports=5000i': invalid field format`});const value=a.sanitizeSlyaCostSourceInfluxError(400,'Bad Request',raw);assert.match(value,/http=400/);assert.match(value,/invalid field format/);assert.doesNotMatch(value,/cargo_cost_source_event_v1|eventIdentity|5KGXN/);assert.ok(value.length<=220);});
test('every existing normal Influx write can carry the outbox without upgrade automation or a new network path',()=>{const scheduled=extract('emitUpgradeAutomationInfluxSnapshot');const perProfile=extract('recordUpgradeAutomationLpPerProfileCompletions');assert.match(source,/SLYA_COST_SOURCE_OUTBOX_KEY/);assert.match(source,/GM\.setValue\(SLYA_COST_SOURCE_OUTBOX_KEY/);assert.match(source,/async function sendToInflux\(msg, bucketOverride = ''\)/);assert.doesNotMatch(scheduled,/idx === 0|includeCostSourceOutbox/);assert.match(perProfile,/await sendToInflux\(line\)/);assert.match(source,/const flushCostSourceOutbox = !String\(bucketOverride \|\| ''\)\.trim\(\)/);assert.doesNotMatch(source,/UPGRADE_AUTOMATION_INFLUX_BUCKET/);assert.match(source,/acknowledgeSlyaCostSourceEventSnapshot/);assert.doesNotMatch(source,/fetch\([^\n]*cargo_cost_source_event_v1|setInterval\([^\n]*cargo_cost_source_event_v1|setTimeout\([^\n]*cargo_cost_source_event_v1/);});
test('both userscript copies remain synchronized for outbox implementation',()=>{const electron=fs.readFileSync(path.join(__dirname,'..','electron-app/app/SLY_Assistant.user.js'),'utf8');for(const name of ['normalizeSlyaCostSourceOutbox','snapshotSlyaCostSourceOutbox','acknowledgeSlyaCostSourceEventSnapshot','composeSlyaScheduledInfluxBody'])assert.ok(electron.includes(`function ${name}(`));});
test('Retry-After and bounded fallback persist eligibility across restart',()=>{const a=api();const out=a.normalizeSlyaCostSourceOutbox({a:{line:'cargo_cost_source_event_v1,a',queuedAtMs:1000}});const snap=a.snapshotSlyaCostSourceOutbox(out,2000);a.deferSlyaCostSourceEventSnapshot(out,snap,'120',2000);assert.equal(out.get('a').retryAfterMs,122000);assert.equal(a.snapshotSlyaCostSourceOutbox(out,121999).length,0);assert.equal(a.snapshotSlyaCostSourceOutbox(a.normalizeSlyaCostSourceOutbox(Object.fromEntries(out)),122000).length,1);const fallback=a.normalizeSlyaCostSourceOutbox({b:{line:'cargo_cost_source_event_v1,b',queuedAtMs:1000}});a.deferSlyaCostSourceEventSnapshot(fallback,a.snapshotSlyaCostSourceOutbox(fallback,2000),'',2000);assert.equal(fallback.get('b').retryAfterMs,32000);});
test('single-flight source claims canonical flush before its first await and concurrent exports retain legacy path',()=>{const fn=extract('sendToInflux');assert.match(fn,/const ownsCostSourceFlush = flushCostSourceOutbox && !slyaCostSourceFlushInFlight;/);assert.match(fn,/if \(ownsCostSourceFlush\) slyaCostSourceFlushInFlight = true;[\s\S]*await loadSlyaCostSourceOutbox/);assert.match(fn,/queuedCostEvents = ownsCostSourceFlush \? snapshotSlyaCostSourceOutbox/);assert.match(fn,/finally \{[\s\S]*slyaCostSourceFlushInFlight = false/);});
test('publisher records actual canonical HTTP attempts and defers exact failed snapshot only',()=>{const fn=extract('sendToInflux');assert.match(fn,/if \(queuedCostEvents\.length\) slyaCostSourceCounters\.attempted \+= queuedCostEvents\.length;[\s\S]*const response = await fetch/);assert.match(fn,/deferSlyaCostSourceEventSnapshot\(costSourceOutbox, queuedCostEvents/);assert.match(fn,/acknowledgeSlyaCostSourceEventSnapshot\(costSourceOutbox, queuedCostEvents\)/);});
function publisherHarness(initial) {
  const writes=[]; let releaseFirst;
  const firstResponse=new Promise(resolve=>{releaseFirst=()=>resolve({ok:true,status:204,statusText:'No Content',headers:{get:()=>null},text:async()=>''});});
  const storage={value:JSON.stringify(initial)};
  const c=vm.createContext({Map,Object,Array,JSON,String,Number,Math,BigInt,URL,Date,Promise,
    globalSettings:{influxURL:'https://example.invalid/api/v2/write?bucket=slya&precision=ms',influxDB:'slya',influxAuth:'token'},
    GM:{getValue:async()=>storage.value,setValue:async(_key,value)=>{storage.value=value;}},
    fetch:async(_url,options)=>{writes.push(options.body);return options.body.includes('cargo_cost_source_event_v1')?firstResponse:{ok:true,status:204,statusText:'No Content',headers:{get:()=>null},text:async()=>''};},
    cLog:()=>{},appendUpgradeAutomationLog:async()=>{},upgradeAutomationInfluxDebugStatus:'',
  });
  const names=['getSlyaInfluxPrecision','formatSlyaInfluxTimestamp','normalizeSlyaCostSourceEventLineTimestamp','normalizeSlyaCostSourceOutbox','snapshotSlyaCostSourceOutbox','parseSlyaCostSourceRetryAfterMs','deferSlyaCostSourceEventSnapshot','acknowledgeSlyaCostSourceEventSnapshot','composeSlyaScheduledInfluxBody','getSlyaCostSourceOldestPendingAgeSeconds','loadSlyaCostSourceOutbox','persistSlyaCostSourceOutbox','buildInfluxWriteUrl','sanitizeSlyaCostSourceInfluxError','sendToInflux'];
  const asyncNames=new Set(['loadSlyaCostSourceOutbox','persistSlyaCostSourceOutbox','sendToInflux']);
  const functions=names.map(name=>asyncNames.has(name)?extract(name).replace(/^function /,'async function '):extract(name));
  vm.runInContext(`const SLYA_COST_SOURCE_OUTBOX_KEY='outbox';let pendingSlyaCostSourceEventLines=null;let slyaCostSourcePersistTail=Promise.resolve();let slyaCostSourceFlushInFlight=false;const SLYA_COST_SOURCE_RETRY_BASE_MS=30000;const SLYA_COST_SOURCE_RETRY_MAX_MS=900000;const slyaCostSourceMissingCounts={};const slyaCostSourceCounters={eligible:0,queued:0,deduplicated:0,attempted:0,accepted:0,failed:0};\n${functions.join('\n')}\nthis.api={sendToInflux,getOutbox:()=>pendingSlyaCostSourceEventLines,getCounters:()=>slyaCostSourceCounters};`,c);
  return {api:c.api,writes,releaseFirst,storage};
}
test('multiple simultaneous normal exports submit the canonical snapshot once',async()=>{const h=publisherHarness({a:{line:'cargo_cost_source_event_v1,eventType=sol_fee a=1i 1785830000000',queuedAtMs:1}});const first=h.api.sendToInflux('legacy first=1i');await Promise.resolve();await Promise.resolve();const second=h.api.sendToInflux('legacy second=1i');await second;assert.equal(h.writes.length,2);assert.equal(h.writes.filter(body=>body.includes('cargo_cost_source_event_v1')).length,1);h.releaseFirst();await first;assert.equal(h.api.getOutbox().size,0);assert.deepEqual({...h.api.getCounters()},{eligible:0,queued:0,deduplicated:0,attempted:1,accepted:1,failed:0});});
test('event queued during an in-flight write is not acknowledged with the submitted snapshot',async()=>{const h=publisherHarness({a:{line:'cargo_cost_source_event_v1,eventType=sol_fee a=1i 1785830000000',queuedAtMs:1}});const write=h.api.sendToInflux('legacy first=1i');for(let i=0;i<10&&!h.writes.length;i+=1)await Promise.resolve();h.api.getOutbox().set('b',{line:'cargo_cost_source_event_v1,eventType=fuel b=1i 1785830000000',queuedAtMs:2,retryAfterMs:0,attemptCount:0});h.releaseFirst();await write;assert.deepEqual([...h.api.getOutbox().keys()],['b']);});
