'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'SLY_Assistant.user.js'), 'utf8');
function extract(name) {
  const start = source.indexOf(`function ${name}(`); assert.notEqual(start, -1, name);
  const body = source.indexOf('{', source.indexOf(')', start)); let depth=0,q='',esc=false;
  for(let i=body;i<source.length;i++){const c=source[i];if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q='';continue;}if('"\'`'.includes(c)){q=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return source.slice(start,i+1);} throw Error(name);
}
function api(){const c=vm.createContext({Map,Object,Array,JSON,String,Number,Math,BigInt,URL,Date,globalSettings:{influxURL:'https://example.invalid/api/v2/write?bucket=slya&precision=ms'},getSlyaInfluxInstanceTag:()=> 'MUD',getUpgradeAutomationInfluxFactionTag:()=> 'MUD',influxEscape:String,optimizationInfluxString:v=>JSON.stringify(String(v??''))});vm.runInContext(`${extract('getSlyaInfluxPrecision')}\n${extract('formatSlyaInfluxTimestamp')}\n${extract('normalizeSlyaCostSourceEventLineTimestamp')}\n${extract('getSlyaCostSourceScope')}\n${extract('getSlyaCostEventTimestamp')}\n${extract('buildSlyaFuelCostSourceEvent')}\n${extract('getSlyaTransactionFeeSourceEvents')}\n${extract('buildSlyaCostSourceEventLine')}\n${extract('normalizeSlyaCostSourceOutbox')}\n${extract('snapshotSlyaCostSourceOutbox')}\n${extract('acknowledgeSlyaCostSourceEventSnapshot')}\n${extract('composeSlyaScheduledInfluxBody')}\n${extract('getSlyaCostSourceOldestPendingAgeSeconds')}\n${extract('sanitizeSlyaCostSourceInfluxError')}\nthis.api={formatSlyaInfluxTimestamp,normalizeSlyaCostSourceEventLineTimestamp,buildSlyaFuelCostSourceEvent,getSlyaTransactionFeeSourceEvents,buildSlyaCostSourceEventLine,normalizeSlyaCostSourceOutbox,snapshotSlyaCostSourceOutbox,acknowledgeSlyaCostSourceEventSnapshot,composeSlyaScheduledInfluxBody,getSlyaCostSourceOldestPendingAgeSeconds,sanitizeSlyaCostSourceInfluxError};`,c);return c.api;}
const tx=(sig,fee=5000,time=1785830000)=>({slyaTxHash:sig,slyaTxFeeLamports:fee,blockTime:time});
const fuelInput={cycleId:'cycle',movementEventId:'cycle:0',movementIndex:0,burnedFuel:12.5,txResult:tx('move'),fleetAccount:'fleet',fleetLabel:'Fleet',assignment:'Transport'};
test('confirmed Fuel and SOL reach normal body and distinct equal-time events remain distinct',()=>{const a=api();const fuel=a.buildSlyaFuelCostSourceEvent(fuelInput);const sol=a.getSlyaTransactionFeeSourceEvents(tx('real'))[0];const out=a.normalizeSlyaCostSourceOutbox({[fuel.eventIdentity]:a.buildSlyaCostSourceEventLine(fuel),[sol.eventIdentity]:a.buildSlyaCostSourceEventLine(sol)});const snap=a.snapshotSlyaCostSourceOutbox(out);const body=a.composeSlyaScheduledInfluxBody('compat x=1i',snap);assert.match(body,/cargo_cost_source_event_v1.*fuel:cycle:0/);assert.match(body,/cargo_cost_source_event_v1.*sol_fee:real/);assert.match(body,/compat x=1i/);assert.match(body,/ 1785830000000(?:\n|$)/);assert.equal(snap.length,2);});
test('legacy outbox strings migrate to durable records with queued time',()=>{const a=api();const legacy='cargo_cost_source_event_v1,eventType=sol_fee,eventIdentity=sol_fee:sig,schemaVersion=1 txFeeLamports=5000i,transactionSignature="sig" 1785830000000000000';const migrated=a.normalizeSlyaCostSourceOutbox({['sol_fee:sig']:legacy}).get('sol_fee:sig');assert.equal(migrated.line,'cargo_cost_source_event_v1,eventType=sol_fee,eventIdentity=sol_fee:sig,schemaVersion=1 txFeeLamports=5000i,transactionSignature="sig" 1785830000000');assert.ok(Number.isSafeInteger(migrated.queuedAtMs));});
test('ack removes exactly accepted snapshot; post-snapshot event remains',()=>{const a=api();const out=a.normalizeSlyaCostSourceOutbox({a:'cargo_cost_source_event_v1,a',b:'cargo_cost_source_event_v1,b'});const snap=a.snapshotSlyaCostSourceOutbox(out);out.set('c',{line:'cargo_cost_source_event_v1,c',queuedAtMs:3});a.acknowledgeSlyaCostSourceEventSnapshot(out,snap);assert.deepEqual([...out.entries()],[['c',{line:'cargo_cost_source_event_v1,c',queuedAtMs:3}]]);});
test('failure retention, restart reload, deterministic dedupe, and pending age are durable',()=>{const a=api();let out=a.normalizeSlyaCostSourceOutbox({a:{line:'cargo_cost_source_event_v1,a',queuedAtMs:1000}});const snap=a.snapshotSlyaCostSourceOutbox(out);assert.equal(out.size,1);out=a.normalizeSlyaCostSourceOutbox(Object.fromEntries(out));if(!out.has('a')) out.set('a',{line:'cargo_cost_source_event_v1,a',queuedAtMs:2000});assert.equal(out.size,1);assert.equal(out.get('a').queuedAtMs,1000);assert.equal(a.getSlyaCostSourceOldestPendingAgeSeconds(out,6000),5);assert.equal(snap.length,1);});
test('Influx rejection diagnostic retains parser reason but redacts payload and identifiers',()=>{const a=api();const secret='5KGXNWa5URbQJKiUuRH4D4nQ581QKfzvUkgpfA98hm3WSs9yi3zJqJtb4bHm4GxfQysBpKzPqh186VXDA1u2j8Zn';const raw=JSON.stringify({code:'invalid',message:`unable to parse 'cargo_cost_source_event_v1,eventIdentity=sol_fee:${secret} txFeeLamports=5000i': invalid field format`});const value=a.sanitizeSlyaCostSourceInfluxError(400,'Bad Request',raw);assert.match(value,/http=400/);assert.match(value,/invalid field format/);assert.doesNotMatch(value,/cargo_cost_source_event_v1|eventIdentity|5KGXN/);assert.ok(value.length<=220);});
test('every existing normal Influx write can carry the outbox without upgrade automation or a new network path',()=>{const scheduled=extract('emitUpgradeAutomationInfluxSnapshot');const perProfile=extract('recordUpgradeAutomationLpPerProfileCompletions');assert.match(source,/SLYA_COST_SOURCE_OUTBOX_KEY/);assert.match(source,/GM\.setValue\(SLYA_COST_SOURCE_OUTBOX_KEY/);assert.match(source,/async function sendToInflux\(msg, bucketOverride = ''\)/);assert.doesNotMatch(scheduled,/idx === 0|includeCostSourceOutbox/);assert.match(perProfile,/await sendToInflux\(line\)/);assert.match(source,/const flushCostSourceOutbox = !String\(bucketOverride \|\| ''\)\.trim\(\)/);assert.doesNotMatch(source,/UPGRADE_AUTOMATION_INFLUX_BUCKET/);assert.match(source,/acknowledgeSlyaCostSourceEventSnapshot/);assert.doesNotMatch(source,/fetch\([^\n]*cargo_cost_source_event_v1|setInterval\([^\n]*cargo_cost_source_event_v1|setTimeout\([^\n]*cargo_cost_source_event_v1/);});
test('both userscript copies remain synchronized for outbox implementation',()=>{const electron=fs.readFileSync(path.join(__dirname,'..','electron-app/app/SLY_Assistant.user.js'),'utf8');for(const name of ['normalizeSlyaCostSourceOutbox','snapshotSlyaCostSourceOutbox','acknowledgeSlyaCostSourceEventSnapshot','composeSlyaScheduledInfluxBody'])assert.ok(electron.includes(`function ${name}(`));});
